// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package __test

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserStatus int32

const (
	UserStatus_Active   UserStatus = 0
	UserStatus_Inactive UserStatus = 1
	UserStatus_Closed   UserStatus = 2
)

var UserStatus_name = map[int32]string{
	0: "Active",
	1: "Inactive",
	2: "Closed",
}

var UserStatus_value = map[string]int32{
	"Active":   0,
	"Inactive": 1,
	"Closed":   2,
}

func (x UserStatus) String() string {
	return proto.EnumName(UserStatus_name, int32(x))
}

func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

type Pong struct {
	God                  []*Pong_God `protobuf:"bytes,1,rep,name=god,proto3" json:"god,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetGod() []*Pong_God {
	if m != nil {
		return m.God
	}
	return nil
}

type Pong_God struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  string   `protobuf:"bytes,2,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong_God) Reset()         { *m = Pong_God{} }
func (m *Pong_God) String() string { return proto.CompactTextString(m) }
func (*Pong_God) ProtoMessage()    {}
func (*Pong_God) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0, 0}
}

func (m *Pong_God) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong_God.Unmarshal(m, b)
}
func (m *Pong_God) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong_God.Marshal(b, m, deterministic)
}
func (m *Pong_God) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong_God.Merge(m, src)
}
func (m *Pong_God) XXX_Size() int {
	return xxx_messageInfo_Pong_God.Size(m)
}
func (m *Pong_God) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong_God.DiscardUnknown(m)
}

var xxx_messageInfo_Pong_God proto.InternalMessageInfo

func (m *Pong_God) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Pong_God) GetAge() string {
	if m != nil {
		return m.Age
	}
	return ""
}

type User struct {
	Name                 string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32           `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Addresses            []*User_Address `protobuf:"bytes,3,rep,name=addresses,proto3" json:"addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *User) GetAddresses() []*User_Address {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type User_Address struct {
	Country              string   `protobuf:"bytes,1,opt,name=Country,proto3" json:"Country,omitempty"`
	Region               string   `protobuf:"bytes,2,opt,name=Region,proto3" json:"Region,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User_Address) Reset()         { *m = User_Address{} }
func (m *User_Address) String() string { return proto.CompactTextString(m) }
func (*User_Address) ProtoMessage()    {}
func (*User_Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{1, 0}
}

func (m *User_Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User_Address.Unmarshal(m, b)
}
func (m *User_Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User_Address.Marshal(b, m, deterministic)
}
func (m *User_Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User_Address.Merge(m, src)
}
func (m *User_Address) XXX_Size() int {
	return xxx_messageInfo_User_Address.Size(m)
}
func (m *User_Address) XXX_DiscardUnknown() {
	xxx_messageInfo_User_Address.DiscardUnknown(m)
}

var xxx_messageInfo_User_Address proto.InternalMessageInfo

func (m *User_Address) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *User_Address) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

type UserWithStatus struct {
	Status               UserStatus `protobuf:"varint,1,opt,name=status,proto3,enum=UserStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UserWithStatus) Reset()         { *m = UserWithStatus{} }
func (m *UserWithStatus) String() string { return proto.CompactTextString(m) }
func (*UserWithStatus) ProtoMessage()    {}
func (*UserWithStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{2}
}

func (m *UserWithStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserWithStatus.Unmarshal(m, b)
}
func (m *UserWithStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserWithStatus.Marshal(b, m, deterministic)
}
func (m *UserWithStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserWithStatus.Merge(m, src)
}
func (m *UserWithStatus) XXX_Size() int {
	return xxx_messageInfo_UserWithStatus.Size(m)
}
func (m *UserWithStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_UserWithStatus.DiscardUnknown(m)
}

var xxx_messageInfo_UserWithStatus proto.InternalMessageInfo

func (m *UserWithStatus) GetStatus() UserStatus {
	if m != nil {
		return m.Status
	}
	return UserStatus_Active
}

func init() {
	proto.RegisterEnum("UserStatus", UserStatus_name, UserStatus_value)
	proto.RegisterType((*Pong)(nil), "Pong")
	proto.RegisterType((*Pong_God)(nil), "Pong.God")
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*User_Address)(nil), "User.Address")
	proto.RegisterType((*UserWithStatus)(nil), "UserWithStatus")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e) }

var fileDescriptor_c161fcfdc0c3ff1e = []byte{
	// 315 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x5d, 0x4b, 0x3a, 0x41,
	0x14, 0xc6, 0xff, 0xeb, 0xbe, 0xa8, 0xc7, 0x7f, 0x22, 0x87, 0x90, 0x65, 0xbd, 0x11, 0x23, 0x90,
	0x84, 0x11, 0x36, 0xba, 0xa9, 0x2b, 0xb3, 0x90, 0xee, 0x64, 0x2b, 0x82, 0xee, 0xd6, 0xf6, 0x34,
	0x2d, 0xe8, 0x8c, 0xec, 0xcc, 0x06, 0x7e, 0x91, 0x3e, 0x6f, 0xcc, 0xec, 0x88, 0x97, 0xdd, 0x9d,
	0xe7, 0xf7, 0xcc, 0x79, 0x61, 0x1e, 0x00, 0x4d, 0x4a, 0xb3, 0x7d, 0x25, 0xb5, 0x4c, 0x46, 0x5c,
	0x4a, 0xbe, 0xa5, 0xb9, 0x55, 0x9b, 0xfa, 0x73, 0x4e, 0xbb, 0xbd, 0x3e, 0x34, 0xe6, 0x64, 0x0d,
	0xc1, 0x5a, 0x0a, 0x8e, 0x23, 0xf0, 0xb9, 0x2c, 0x62, 0x6f, 0xec, 0x4f, 0x7b, 0x69, 0x97, 0x19,
	0xc6, 0x56, 0xb2, 0xc8, 0x0c, 0x4d, 0x66, 0xe0, 0xaf, 0x64, 0x81, 0x08, 0x81, 0xc8, 0x77, 0x14,
	0x7b, 0x63, 0x6f, 0xda, 0xcd, 0x6c, 0x8d, 0x03, 0xf0, 0x73, 0x4e, 0x71, 0xcb, 0x22, 0x53, 0x4e,
	0x7e, 0x3c, 0x08, 0x5e, 0x15, 0x55, 0x7f, 0x3d, 0x0f, 0xed, 0x73, 0x9c, 0x41, 0x37, 0x2f, 0x8a,
	0x8a, 0x94, 0x22, 0x15, 0xfb, 0x76, 0xfd, 0x19, 0x33, 0xfd, 0x6c, 0xd1, 0xe0, 0xec, 0xe4, 0x27,
	0x77, 0xd0, 0x76, 0x14, 0x63, 0x68, 0x2f, 0x65, 0x2d, 0x74, 0x75, 0x70, 0x0b, 0x8e, 0x12, 0x87,
	0x10, 0x65, 0xc4, 0x4b, 0x29, 0xdc, 0x55, 0x4e, 0x4d, 0x6e, 0xa0, 0x6f, 0xe6, 0xbe, 0x95, 0xfa,
	0xeb, 0x59, 0xe7, 0xba, 0x56, 0x78, 0x01, 0x91, 0xb2, 0x95, 0x1d, 0xd1, 0x4f, 0x7b, 0x76, 0x71,
	0x63, 0x66, 0xce, 0xba, 0x4a, 0x01, 0x4e, 0x14, 0x01, 0xa2, 0xc5, 0x87, 0x2e, 0xbf, 0x69, 0xf0,
	0x0f, 0xff, 0x43, 0xe7, 0x49, 0xe4, 0x8d, 0xf2, 0x8c, 0xb3, 0xdc, 0x4a, 0x45, 0xc5, 0xa0, 0x95,
	0x3e, 0x40, 0x68, 0x7a, 0x14, 0x5e, 0x42, 0xb0, 0x2e, 0x05, 0xc7, 0x21, 0x6b, 0x42, 0x60, 0xc7,
	0x10, 0xd8, 0xa3, 0x09, 0x21, 0x09, 0xed, 0x4f, 0xe3, 0x39, 0x04, 0x2f, 0xa4, 0x34, 0x86, 0xf6,
	0x00, 0x47, 0xef, 0x3b, 0xef, 0x11, 0xbb, 0x35, 0x41, 0x6e, 0x22, 0xdb, 0x76, 0xfd, 0x1b, 0x00,
	0x00, 0xff, 0xff, 0x60, 0x2f, 0x25, 0xb4, 0xd7, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UsersClient is the client API for Users service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UsersClient interface {
	Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Pong, error)
	Test(ctx context.Context, in *User, opts ...grpc.CallOption) (*Pong, error)
}

type usersClient struct {
	cc *grpc.ClientConn
}

func NewUsersClient(cc *grpc.ClientConn) UsersClient {
	return &usersClient{cc}
}

func (c *usersClient) Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Pong, error) {
	out := new(Pong)
	err := c.cc.Invoke(ctx, "/Users/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) Test(ctx context.Context, in *User, opts ...grpc.CallOption) (*Pong, error) {
	out := new(Pong)
	err := c.cc.Invoke(ctx, "/Users/Test", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersServer is the server API for Users service.
type UsersServer interface {
	Ping(context.Context, *empty.Empty) (*Pong, error)
	Test(context.Context, *User) (*Pong, error)
}

// UnimplementedUsersServer can be embedded to have forward compatible implementations.
type UnimplementedUsersServer struct {
}

func (*UnimplementedUsersServer) Ping(ctx context.Context, req *empty.Empty) (*Pong, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedUsersServer) Test(ctx context.Context, req *User) (*Pong, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Test not implemented")
}

func RegisterUsersServer(s *grpc.Server, srv UsersServer) {
	s.RegisterService(&_Users_serviceDesc, srv)
}

func _Users_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Users/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).Ping(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_Test_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).Test(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Users/Test",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).Test(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

var _Users_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Users",
	HandlerType: (*UsersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Users_Ping_Handler,
		},
		{
			MethodName: "Test",
			Handler:    _Users_Test_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test.proto",
}
